name: 01 - Test and Build

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"

  schedule:
  - cron: 0 2 * * 3,6

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ORACLE_HOME: /opt/instantclient_23_8
      LD_LIBRARY_PATH: /opt/instantclient_23_8
      OCI_DIR: /opt/instantclient_23_8
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
          check-latest: true

      - name: Install Oracle instant client
        run: |
          mkdir -p /opt && cd /opt
          curl https://download.oracle.com/otn_software/linux/instantclient/2380000/instantclient-basic-linux.x64-23.8.0.25.04.zip --output instantclient.zip
          curl https://download.oracle.com/otn_software/linux/instantclient/2380000/instantclient-sdk-linux.x64-23.8.0.25.04.zip --output instantclient_sdk.zip
          unzip -o instantclient.zip
          unzip -o instantclient_sdk.zip

      - name: Install go tools for linting and vulnerability check
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Build
        run: make test build