name: cd

on:
  release:
    types: [ published ]

jobs:
  linux:
    name: Release for Linux
    runs-on: ubuntu-latest
    env:
      ORACLE_HOME: /opt/instantclient_21_7
      LD_LIBRARY_PATH: /opt/instantclient_21_7
      OCI_DIR: /opt/instantclient_21_7
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Install Oracle instant client
        run: |
          mkdir -p /opt && cd /opt
          curl https://download.oracle.com/otn_software/linux/instantclient/217000/instantclient-basic-linux.x64-21.7.0.0.0dbru.zip --output instantclient.zip
          curl https://download.oracle.com/otn_software/linux/instantclient/217000/instantclient-sdk-linux.x64-21.7.0.0.0dbru.zip --output instantclient_sdk.zip
          unzip instantclient.zip
          unzip instantclient_sdk.zip

      - name: Install staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Build
        run: |
          make clean_release test lint build_linux_amd64

      - name: Upload release for linux amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./releases/sensu-checks-go.linux.amd64.tar.gz
          asset_name: sensu-checks-go.linux.amd64.tar.gz
          asset_content_type: application/gzip

      - name: Upload checksum for linux amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./releases/sensu-checks-go.linux.amd64.tar.gz.sha512
          asset_name: sensu-checks-go.linux.amd64.tar.gz.sha512
          asset_content_type: text/plain

  macOS:
    name: Release for macOS
    runs-on: macos-latest
    env:
      ORACLE_HOME: ~/opt/instantclient_19_8
      LD_LIBRARY_PATH: ~/opt/instantclient_19_8
      OCI_DIR: ~/opt/instantclient_19_8
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Install Oracle instant client
        run: |
          mkdir -p ~/opt
          curl https://download.oracle.com/otn_software/mac/instantclient/198000/instantclient-basic-macos.x64-19.8.0.0.0dbru.zip --output ~/opt/instantclient.zip
          curl https://download.oracle.com/otn_software/mac/instantclient/198000/instantclient-sdk-macos.x64-19.8.0.0.0dbru.zip --output ~/opt/instantclient_sdk.zip
          unzip ~/opt/instantclient.zip -d ~/opt
          unzip ~/opt/instantclient_sdk.zip -d ~/opt

      - name: Install staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Build
        run: |
          echo -e "#!/bin/sh\nshasum -a 512 $1" > /usr/local/bin/sha512sum && chmod +x /usr/local/bin/sha512sum
          make clean_release test lint
          make build_darwin_amd64
          make build_darwin_arm64

      - name: Upload release for darwin amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./releases/sensu-checks-go.darwin.amd64.tar.gz
          asset_name: sensu-checks-go.darwin.amd64.tar.gz
          asset_content_type: application/gzip

      - name: Upload checksum for darwin amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./releases/sensu-checks-go.darwin.amd64.tar.gz.sha512
          asset_name: sensu-checks-go.darwin.amd64.tar.gz.sha512
          asset_content_type: text/plain

      - name: Upload release for darwin arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./releases/sensu-checks-go.darwin.arm64.tar.gz
          asset_name: sensu-checks-go.darwin.arm64.tar.gz
          asset_content_type: application/gzip

      - name: Upload checksum for darwin arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./releases/sensu-checks-go.darwin.arm64.tar.gz.sha512
          asset_name: sensu-checks-go.darwin.arm64.tar.gz.sha512
          asset_content_type: text/plain
