name: cd

on:
  release:
    types: [ published ]

jobs:
  linux:
    name: Release for Linux
    runs-on: ubuntu-latest
    env:
      ORACLE_HOME: /opt/instantclient_21_8
      LD_LIBRARY_PATH: /opt/instantclient_21_8
      OCI_DIR: /opt/instantclient_21_8
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.6'
          check-latest: true

      - name: Install Oracle instant client
        run: |
          mkdir -p /opt && cd /opt
          curl https://download.oracle.com/otn_software/linux/instantclient/218000/instantclient-basic-linux.x64-21.8.0.0.0dbru.zip --output instantclient.zip
          curl https://download.oracle.com/otn_software/linux/instantclient/218000/instantclient-sdk-linux.x64-21.8.0.0.0dbru.zip --output instantclient_sdk.zip
          unzip instantclient.zip
          unzip instantclient_sdk.zip

      - name: Install staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Install govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Build
        run: |
          make clean_release test lint vul
          make build_linux_amd64
          make build_linux_arm64

      - name: Upload release for linux amd64
        uses: softprops/action-gh-release@v2
        with:
          files: |
            releases/sensu-checks-go.linux.amd64.tar.gz
            releases/sensu-checks-go.linux.amd64.tar.gz.sha512

      - name: Upload release for linux arm64
        uses: softprops/action-gh-release@v2
        with:
          files: |
            releases/sensu-checks-go.linux.arm64.tar.gz
            releases/sensu-checks-go.linux.arm64.tar.gz.sha512

  macOS:
    name: Release for macOS (ARM)
    runs-on: macos-14
    env:
      ORACLE_HOME: ~/opt/instantclient_19_8
      LD_LIBRARY_PATH: ~/opt/instantclient_19_8
      OCI_DIR: ~/opt/instantclient_19_8
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
          check-latest: true

      - name: Install Oracle instant client
        run: |
          mkdir -p ~/opt
          curl https://download.oracle.com/otn_software/mac/instantclient/198000/instantclient-basic-macos.x64-19.8.0.0.0dbru.zip --output ~/opt/instantclient.zip
          curl https://download.oracle.com/otn_software/mac/instantclient/198000/instantclient-sdk-macos.x64-19.8.0.0.0dbru.zip --output ~/opt/instantclient_sdk.zip
          unzip ~/opt/instantclient.zip -d ~/opt
          unzip ~/opt/instantclient_sdk.zip -d ~/opt

      - name: Install staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Install govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Build
        run: |
          echo -e "#!/bin/sh\nshasum -a 512 $1" > /usr/local/bin/sha512sum && chmod +x /usr/local/bin/sha512sum
          make clean_release test lint vul
          make build_darwin_amd64
          make build_darwin_arm64

      - name: Upload release for darwin amd64
        uses: softprops/action-gh-release@v2
        with:
          files: |
            releases/sensu-checks-go.darwin.amd64.tar.gz
            releases/sensu-checks-go.darwin.amd64.tar.gz.sha512

      - name: Upload release for darwin arm64
        uses: softprops/action-gh-release@v2
        with:
          files: |
            releases/sensu-checks-go.darwin.arm64.tar.gz
            releases/sensu-checks-go.darwin.arm64.tar.gz.sha512
