name: cd
on:
  release:
    types: [ published ]
jobs:
  linux:
    name: Release for Linux
    runs-on: ubuntu-latest
    env:
      ORACLE_HOME: /opt/instantclient_23_8
      LD_LIBRARY_PATH: /opt/instantclient_23_8
      OCI_DIR: /opt/instantclient_23_8
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
          check-latest: true
      - name: Install Oracle instant client
        run: |
          sudo mkdir -p /opt && cd /opt
          sudo curl https://download.oracle.com/otn_software/linux/instantclient/2380000/instantclient-basic-linux.x64-23.8.0.25.04.zip --output instantclient.zip
          sudo curl https://download.oracle.com/otn_software/linux/instantclient/2380000/instantclient-sdk-linux.x64-23.8.0.25.04.zip --output instantclient_sdk.zip
          sudo unzip -o instantclient.zip
          sudo unzip -o instantclient_sdk.zip
      - name: Install staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Install govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Build
        run: |
          make clean_release test lint vul
          make build_linux_amd64
          make build_linux_arm64
      - name: Upload release for linux amd64
        uses: softprops/action-gh-release@v2
        with:
          files: |
            releases/sensu-checks-go.linux.amd64.tar.gz
            releases/sensu-checks-go.linux.amd64.tar.gz.sha512
      - name: Upload release for linux arm64
        uses: softprops/action-gh-release@v2
        with:
          files: |
            releases/sensu-checks-go.linux.arm64.tar.gz
            releases/sensu-checks-go.linux.arm64.tar.gz.sha512
  macOS:
    name: Release for macOS (ARM)
    runs-on: macos-14
    env:
      ORACLE_HOME: /opt/oracle/instantclient_23_3
      DYLD_LIBRARY_PATH: /opt/oracle/instantclient_23_3
      OCI_DIR: /opt/oracle/instantclient_23_3
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
          check-latest: true
      - name: Install Oracle instant client
        run: |
          # Download the Basic and SDK DMG files (23.3.0.23.09)
          curl -L -o instantclient-basic.dmg https://download.oracle.com/otn_software/mac/instantclient/instantclient-basic-macos-arm64.dmg
          curl -L -o instantclient-sdk.dmg https://download.oracle.com/otn_software/mac/instantclient/instantclient-sdk-macos-arm64.dmg

          # Mount the DMG files
          hdiutil mount instantclient-basic.dmg
          hdiutil mount instantclient-sdk.dmg

          # Create destination directory
          sudo mkdir -p /opt/oracle/instantclient_23_3

          # Copy files from mounted volumes to destination
          # The DMG contains the files in a subdirectory structure
          sudo cp -R /Volumes/instantclient-basic-macos.arm64-23.3.0.23.09/* /opt/oracle/instantclient_23_3/
          sudo cp -R /Volumes/instantclient-sdk-macos.arm64-23.3.0.23.09/sdk /opt/oracle/instantclient_23_3/

          # Create symbolic links for compatibility
          cd /opt/oracle/instantclient_23_3
          sudo ln -sf libclntsh.dylib.23.1 libclntsh.dylib
          sudo ln -sf libocci.dylib.23.1 libocci.dylib

          # Unmount the DMG files
          hdiutil unmount /Volumes/instantclient-basic-macos.arm64-23.3.0.23.09 || true
          hdiutil unmount /Volumes/instantclient-sdk-macos.arm64-23.3.0.23.09 || true

          # Clean up DMG files
          rm -f instantclient-basic.dmg instantclient-sdk.dmg
      - name: Install staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Install govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Build
        run: |
          sudo sh -c 'echo "#!/bin/sh\nshasum -a 512 \$1" > /usr/local/bin/sha512sum && chmod +x /usr/local/bin/sha512sum'
          make clean_release test lint vul
          make build_darwin_amd64
          make build_darwin_arm64
      - name: Upload release for darwin amd64
        uses: softprops/action-gh-release@v2
        with:
          files: |
            releases/sensu-checks-go.darwin.amd64.tar.gz
            releases/sensu-checks-go.darwin.amd64.tar.gz.sha512
      - name: Upload release for darwin arm64
        uses: softprops/action-gh-release@v2
        with:
          files: |
            releases/sensu-checks-go.darwin.arm64.tar.gz
            releases/sensu-checks-go.darwin.arm64.tar.gz.sha512
