name: ci

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"

  schedule:
  - cron: 0 2 * * 1,3,5,6

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ORACLE_HOME: /opt/instantclient_21_8
      LD_LIBRARY_PATH: /opt/instantclient_21_8
      OCI_DIR: /opt/instantclient_21_8
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
          check-latest: true

      - name: Install Oracle instant client
        run: |
          mkdir -p /opt && cd /opt
          curl https://download.oracle.com/otn_software/linux/instantclient/218000/instantclient-basic-linux.x64-21.8.0.0.0dbru.zip --output instantclient.zip
          curl https://download.oracle.com/otn_software/linux/instantclient/218000/instantclient-sdk-linux.x64-21.8.0.0.0dbru.zip --output instantclient_sdk.zip
          unzip instantclient.zip
          unzip instantclient_sdk.zip

      - name: Install go tools for linting and vulnerability check
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Build
        run: make format test lint build

      # - name: Check vulnerabilities
      #   # expected to have binaries build before
      #   run: make vul
