name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  schedule:
  - cron: 0 2 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Build
        run: make
